# --- builder ---
FROM node:20-alpine AS builder
RUN corepack enable
WORKDIR /app
COPY package.json pnpm-workspace.yaml turbo.json prettier.config.cjs ./
COPY packages ./packages
COPY apps/web/package.json ./apps/web/package.json
COPY apps/api/package.json ./apps/api/package.json
RUN pnpm install --frozen-lockfile || pnpm install
COPY apps ./apps
COPY packages ./packages
WORKDIR /app/apps/web
RUN pnpm install --frozen-lockfile=false
RUN pnpm run build  # -> génère /app/apps/web/dist

# --- runner ---
FROM nginx:alpine AS runner
COPY infra/docker/nginx.vite.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html
